//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adoptie
    {
        public int AdoptieId { get; set; }
        public string NrInregistrare { get; set; }
        public int CaineId { get; set; }
        public int PersoanaId { get; set; }
        public System.DateTime DataAdoptie { get; set; }
        public string UserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Persoana Persoana { get; set; }
        public virtual Caine Caine { get; set; }
    }
}
