//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserDetaliu> UserDetalius { get; set; }
        public virtual DbSet<Persoana> Persoanas { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Judet> Judets { get; set; }
        public virtual DbSet<Localitate> Localitates { get; set; }
        public virtual DbSet<PersoanaDetaliu> PersoanaDetalius { get; set; }
        public virtual DbSet<Adoptie> Adopties { get; set; }
        public virtual DbSet<Caine> Caines { get; set; }
    }
}
