//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersoanaDetaliu
    {
        public int PersoanaId { get; set; }
        public string Adresa { get; set; }
        public bool LocuintaCurte { get; set; }
        public int LocalitateID { get; set; }
    
        public virtual Persoana Persoana { get; set; }
        public virtual Localitate Localitate { get; set; }
    }
}
